// build.js
// Usage: node build.js
// Inlines CSS and JS source files into a single distributable HTML file.

const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'main');
const jsSrcDir = path.join(srcDir, 'js');
const cssSrcDir = path.join(srcDir, 'css');
const distDir = path.join(__dirname, 'dist');
const htmlSrcPath = path.join(srcDir, 'index.html');
const htmlDistPath = path.join(distDir, 'aiTemplateLab.html');

// Explicit load order — do not change without updating index.html <link> tags too.
const CSS_FILES_ORDERED = [
    'variables.css',
    'base.css',
    'layout.css',
    'sidebar.css',
    'components.css',
    'forms.css',
    'modals.css',
    'screens.css',
];

// Explicit load order — do not change without updating index.html <script> tags too.
const JS_FILES_ORDERED = [
    'utils.js',
    'state.js',
    'storage.js',
    'screens.js',
    'editPrompt.js',
    'preloadedPrompts.js',
    'promptOutput.js',
    'promptCrud.js',
    'importExport.js',
    'workspaceManager.js',
    'app.js',
];

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);

// =========================
// Generate preloadedPrompts.js from Prompts/ + config/workspaces.json
// =========================
const promptsDir = path.join(srcDir, 'Prompts');
const workspacesConfigPath = path.join(srcDir, 'config', 'workspaces.json');
const workspacesConfig = JSON.parse(fs.readFileSync(workspacesConfigPath, 'utf8'));

const loadedPromptFiles = {}; // filename -> prompt[]
for (const fileList of Object.values(workspacesConfig.workspaces)) {
    for (const fileName of fileList) {
        if (loadedPromptFiles[fileName]) continue;
        const filePath = path.join(promptsDir, fileName);
        if (!fs.existsSync(filePath)) {
            console.warn(`Warning: Prompt file not found: ${fileName}`);
            loadedPromptFiles[fileName] = [];
        } else {
            const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            loadedPromptFiles[fileName] = Array.isArray(data) ? data : [data];
        }
    }
}

const preloadedWorkspaces = {};
for (const [wsName, fileList] of Object.entries(workspacesConfig.workspaces)) {
    preloadedWorkspaces[wsName] = {
        templates: fileList.flatMap(f => loadedPromptFiles[f] || []),
        inputHistory: []
    };
}

const allPrompts = Object.values(loadedPromptFiles).flat();

const generatedPreloaded = `// AUTO-GENERATED by build.js — edit files in main/Prompts/ and main/config/workspaces.json instead.

window.preloadedPrompts = ${JSON.stringify(allPrompts, null, 4)};

window.preloadedWorkspaces = ${JSON.stringify(preloadedWorkspaces, null, 4)};

window.preloadedConfig = ${JSON.stringify({
    defaultWorkspace: workspacesConfig.defaultWorkspace,
    defaultTemplate: workspacesConfig.defaultTemplate
}, null, 4)};
`;

console.log(`Loaded ${allPrompts.length} prompt(s) across ${Object.keys(preloadedWorkspaces).length} workspace(s)`);

// =========================
// Build HTML
// =========================
let html = fs.readFileSync(htmlSrcPath, 'utf8');

// Resolve HTML partials: <!-- #include "path/to/partial.html" -->
html = html.replace(/<!--\s*#include\s+"([^"]+)"\s*-->/g, (match, includePath) => {
    const fullPath = path.join(srcDir, includePath);
    if (!fs.existsSync(fullPath)) {
        console.warn(`Warning: HTML partial not found: ${includePath}`);
        return `<!-- missing: ${includePath} -->`;
    }
    return fs.readFileSync(fullPath, 'utf8');
});

// Inline CSS — replace the entire block of <link> tags with one <style> block
const cssChunks = [];
for (const cssFile of CSS_FILES_ORDERED) {
    const fullPath = path.join(cssSrcDir, cssFile);
    if (!fs.existsSync(fullPath)) {
        console.warn(`Warning: ${cssFile} not found, skipping`);
        continue;
    }
    cssChunks.push(`/* === ${cssFile} === */\n${fs.readFileSync(fullPath, 'utf8')}`);
}
const combinedCss = cssChunks.join('\n\n');

// Replace the first <link rel="stylesheet" ...> through the last one with a single <style>
html = html.replace(
    /(\s*<link rel="stylesheet" href="css\/[^"]+">)+/,
    `\n    <style>\n${combinedCss}\n    </style>`
);

// Inline JS in explicit order
for (const jsFile of JS_FILES_ORDERED) {
    const jsPath = path.join('js', jsFile).replace(/\\/g, '/');
    const jsContent = jsFile === 'preloadedPrompts.js'
        ? generatedPreloaded
        : fs.existsSync(path.join(jsSrcDir, jsFile))
            ? fs.readFileSync(path.join(jsSrcDir, jsFile), 'utf8')
            : null;
    if (!jsContent) { console.warn(`Warning: ${jsFile} not found, skipping`); continue; }
    const scriptRegex = new RegExp(`<script src=["']${jsPath}["']><\\/script>`, 'i');
    html = html.replace(scriptRegex, `<script>\n${jsContent}\n</script>`);
}

fs.writeFileSync(htmlDistPath, html, 'utf8');
console.log('Build complete: dist/PromptBuilderPro.html');
