/**
 * build.js
 * Usage: node build.js
 *
 * Produces a single self-contained HTML file at dist/aiTemplateLab.html by:
 *   1. Generating prompt data from main/Prompts/*.json + main/config/workspaces.json
 *   2. Resolving <!-- #include "..." --> HTML partial directives
 *   3. Inlining all CSS files into one <style> block
 *   4. Inlining all JS files as individual <script> blocks
 *
 * To add a prompt:    create a JSON file in main/Prompts/ and reference it in workspaces.json.
 * To add a CSS file:  add it to CSS_FILES_ORDERED and to the <link> tags in index.html.
 * To add a JS file:   add it to JS_FILES_ORDERED and to the <script> tags in index.html.
 */

const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'main');
const jsSrcDir = path.join(srcDir, 'js');
const cssSrcDir = path.join(srcDir, 'css');
const distDir = path.join(__dirname, 'dist');
const docsDir = path.join(__dirname, 'docs');
const htmlSrcPath = path.join(srcDir, 'index.html');
const htmlDistPath = path.join(distDir, 'aiTemplateLab.html');
const htmlDocsPath = path.join(docsDir, 'index.html');

// CSS load order — must match the <link> tags in index.html.
const CSS_FILES_ORDERED = [
    'variables.css',  // CSS custom properties (tokens) — must be first
    'base.css',
    'layout.css',
    'sidebar.css',
    'components.css',
    'forms.css',
    'modals.css',
    'screens.css',
];

// JS load order — must match the <script> tags in index.html.
// Each file depends on the ones above it; do not reorder without checking deps.
const JS_FILES_ORDERED = [
    'utils.js',           // escapeHtml, downloadJson, renderCheckboxGrid
    'state.js',           // shared variables, syncWindowState, normalizePrompt
    'storage.js',         // localStorage read/write/reset
    'screens.js',         // screen/tab switching, clearForm
    'editPrompt.js',      // edit form field management, auto-save
    'preloadedPrompts.js',// AUTO-GENERATED — do not create this file manually
    'promptOutput.js',    // generateViewPrompt, input history
    'promptCrud.js',      // CRUD, viewPrompt, renderPromptsList, drag-drop
    'importExport.js',    // import/export modals, JSON paste modal
    'workspaceManager.js',// template groups, workspace save/load, app-bar menu
    'app.js',             // entry point — init + all event wiring
];

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);
if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir);

// =========================
// Step 1: Generate prompt data from source JSON files
// =========================

const promptsDir = path.join(srcDir, 'Prompts');
const workspacesConfigPath = path.join(srcDir, 'config', 'workspaces.json');
const workspacesConfig = JSON.parse(fs.readFileSync(workspacesConfigPath, 'utf8'));

// Load each unique prompt file referenced by workspaces.json.
const loadedPromptFiles = {}; // filename -> prompt[]
for (const fileList of Object.values(workspacesConfig.workspaces)) {
    for (const fileName of fileList) {
        if (loadedPromptFiles[fileName]) continue; // already loaded
        const filePath = path.join(promptsDir, fileName);
        if (!fs.existsSync(filePath)) {
            console.warn(`Warning: Prompt file not found: ${fileName}`);
            loadedPromptFiles[fileName] = [];
        } else {
            const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            // Accept either a plain object or an array of objects.
            loadedPromptFiles[fileName] = Array.isArray(data) ? data : [data];
        }
    }
}

// Build the workspace map: { [groupName]: { templates: [...], inputHistory: [] } }
const preloadedWorkspaces = {};
for (const [wsName, fileList] of Object.entries(workspacesConfig.workspaces)) {
    preloadedWorkspaces[wsName] = {
        templates: fileList.flatMap(f => loadedPromptFiles[f] || []),
        inputHistory: []
    };
}

const allPrompts = Object.values(loadedPromptFiles).flat();

// Build the JS content that will be injected in place of preloadedPrompts.js.
const generatedPreloaded = `// AUTO-GENERATED by build.js — edit files in main/Prompts/ and main/config/workspaces.json instead.

window.preloadedPrompts = ${JSON.stringify(allPrompts, null, 4)};

window.preloadedWorkspaces = ${JSON.stringify(preloadedWorkspaces, null, 4)};

window.preloadedConfig = ${JSON.stringify({
    defaultWorkspace: workspacesConfig.defaultWorkspace,
    defaultTemplate: workspacesConfig.defaultTemplate
}, null, 4)};
`;

console.log(`Loaded ${allPrompts.length} prompt(s) across ${Object.keys(preloadedWorkspaces).length} workspace(s)`);

// =========================
// Step 2: Resolve HTML partials
// =========================

let html = fs.readFileSync(htmlSrcPath, 'utf8');

// Replace <!-- #include "path/to/partial.html" --> with the file's contents.
html = html.replace(/<!--\s*#include\s+"([^"]+)"\s*-->/g, (match, includePath) => {
    const fullPath = path.join(srcDir, includePath);
    if (!fs.existsSync(fullPath)) {
        console.warn(`Warning: HTML partial not found: ${includePath}`);
        return `<!-- missing: ${includePath} -->`;
    }
    return fs.readFileSync(fullPath, 'utf8');
});

// =========================
// Step 3: Inline CSS
// =========================

const cssChunks = [];
for (const cssFile of CSS_FILES_ORDERED) {
    const fullPath = path.join(cssSrcDir, cssFile);
    if (!fs.existsSync(fullPath)) {
        console.warn(`Warning: ${cssFile} not found, skipping`);
        continue;
    }
    // Section markers make it easy to find a file's rules in browser DevTools.
    cssChunks.push(`/* === ${cssFile} === */\n${fs.readFileSync(fullPath, 'utf8')}`);
}
const combinedCss = cssChunks.join('\n\n');

// Replace all <link rel="stylesheet"> tags with a single <style> block.
html = html.replace(
    /(\s*<link rel="stylesheet" href="css\/[^"]+">)+/,
    `\n    <style>\n${combinedCss}\n    </style>`
);

// =========================
// Step 4: Inline JavaScript
// =========================

for (const jsFile of JS_FILES_ORDERED) {
    const jsPath = path.join('js', jsFile).replace(/\\/g, '/');
    // preloadedPrompts.js is generated in memory (Step 1) — no file on disk.
    const jsContent = jsFile === 'preloadedPrompts.js'
        ? generatedPreloaded
        : fs.existsSync(path.join(jsSrcDir, jsFile))
            ? fs.readFileSync(path.join(jsSrcDir, jsFile), 'utf8')
            : null;
    if (!jsContent) { console.warn(`Warning: ${jsFile} not found, skipping`); continue; }
    // Strip ES module `export` keywords — source files use them for Vitest imports,
    // but the browser build inlines everything into plain <script> tags (not modules).
    const strippedContent = jsContent.replace(/^export\s+/gm, '');
    const scriptRegex = new RegExp(`<script src=["']${jsPath}["']><\\/script>`, 'i');
    html = html.replace(scriptRegex, `<script>\n${strippedContent}\n</script>`);
}

fs.writeFileSync(htmlDistPath, html, 'utf8');
fs.writeFileSync(htmlDocsPath, html, 'utf8');
console.log(`Build complete: ${htmlDistPath}`);
console.log(`GitHub Pages:  ${htmlDocsPath}`);
